#!/bin/sh

export LLVM_PROFILE_FILE="/tmp/file.profraw"

cc=clang
output=../mrustc/output
mrustc=mrustc
ccflags=
updatedocs=
rustflags=
filter=

. scripts/parse_params.sh || exit 1;

if [ "$test" = "1" ] || [ "$fasttest" = "1" ] || [ "$coverage" = "1" ]; then
	cd c
	for file in *.c
	do
		if [ "${file}" != "main.c" ]; then
			${cc} ${ccflags} -o ../.obj/${file%.c}.o -c -Ic ${file}
		fi
	done
	cd ..
fi
if [ "$all" = "1" ]; then
	echo "not implemented"
fi
