name: CI Pipeline
on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - '*'
  schedule:
    - cron: "15 7 * * *" # Nightly build at 7:15 AM (UDT)
  workflow_dispatch:  # This enables manual triggering

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux-amd64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check linux version
        run: uname -a
      - name: linux update nightly
        run: rustup install nightly
      - name: linux build (rustc)
        run: |
          ./fam
      - name: linux build (mrustc)
        run: |
          git clone https://github.com/cgilliard/rust-bins
          ./fam --mrustc --with-mrustc=./rust-bins/linux/mrustc --output=./rust-bins/linux/output
      - name: linux tests
        run: |
          ./fam fasttest
      - name: linux code coverage dependencies
        run: |
          cargo install grcov
          rustup component add llvm-tools-preview
      - name: code coverage
        run: |
          git clone https://anything:${{ secrets.FamPat }}@github.com/cgilliard/fam.git _coverage
          cd _coverage
          git config user.name "Coverage-Bot"
          git config user.email "noreply@pipeline.com"
          git checkout main
          ./fam coverage --update-docs
          git commit -am "Coverage-Bot: Updated repo (via main.yml script) Source Version is $GITHUB_SHA";
          if [[ "$GITHUB_EVENT_NAME" == "schedule" || "$GITHUB_EVENT_NAME" == "workflow_dispatch" ]]; then
            git push https://${{ secrets.FamPat }}@github.com/cgilliard/fam.git
          fi
      - name: linux bootstrap (mrustc)
        run: |
          if [[ "$GITHUB_EVENT_NAME" == "schedule" || "$GITHUB_EVENT_NAME" == "workflow_dispatch" ]]; then
            git clone https://github.com/cgilliard/famc
            cd famc
            ./build.sh
            cd ..
            ./fam --mrustc --with-mrustc=./famc/bin/mrustc --output=./famc/output
          fi

  macos:
    runs-on: macos-15-large
    strategy:
      matrix:
        platform: [macos]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check macos version
        run: sw_vers
      - name: macos update nightly
        run: rustup install nightly
      - name: macos build (rustc)
        run: |
          ./fam
      - name: macos build (mrustc)
        run: |
          git clone https://github.com/cgilliard/rust-bins
          ./fam --mrustc --with-mrustc=./rust-bins/macos/mrustc --output=./rust-bins/macos/output
      - name: macos tests
        run: |
          ./fam fasttest
      - name: macos bootstrap (mrustc)
        run: |
          if [[ "$GITHUB_EVENT_NAME" == "schedule" || "$GITHUB_EVENT_NAME" == "workflow_dispatch" ]]; then
            git clone https://github.com/cgilliard/famc
            cd famc
            ./build.sh
            cd ..
            ./fam --mrustc --with-mrustc=./famc/bin/mrustc --output=./famc/output
          fi
